<?php
/**
 * The template for displaying the navbar on the site.
 * It does not use tailwind, it's SCSS file can be found at ./assets/src/sass/components/navbar.scss.
 * The Navbar generated by PHP can be configured in functions.php.
 *
 * This is the template that displays all of the <head> section and everything up until the main body.
 *
 * @link https://developer.wordpress.org/themes/basics/template-files/#template-partials
 *
 * @package WordPress
 * @subpackage Pre_Launch_WP
 * @since 1.0.0
 */

?>
<!doctype html>
<html <?php language_attributes(); ?>>
<head>
    <!--Meta Info-->
    <meta charset="<?php bloginfo('charset'); ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="profile" href="https://gmpg.org/xfn/11">

    <!--Font Awesome Loadin-->
    <script src="https://kit.fontawesome.com/e9f0a6af17.js" crossorigin="anonymous"></script>

    <!--Wordpress Required Stuff-->
    <?php wp_head(); ?>
</head>

<!--Open Body, Apply any Tailwind classes that are global here, Leave WP stuff alone. -->
<body class="tracking-normal leading-normal"
      style="font-family: 'Source Sans Pro', sans-serif;" <?php body_class(); ?>>
<?php wp_body_open(); ?>


<!-- Start Navbar -->
<header class="site-header">
	<div class="nav-shell">
		<a class="nav-brand" href="<?php echo esc_url(home_url('/')); ?>">
			<?php
            $logo = function_exists('get_field') ? get_field('site_nav_logo', 'option') : null;

if (is_array($logo) && !empty($logo['url'])) : ?>
				<img
					class="nav-brand-logo"
					src="<?php echo esc_url($logo['url']); ?>"
					alt="<?php echo esc_attr(!empty($logo['alt']) ? $logo['alt'] : get_bloginfo('name')); ?>"
					loading="eager"
					decoding="async"
				/>
			<?php else : ?>
				<span class="nav-brand-text"><?php echo esc_html(get_bloginfo('name')); ?></span>
			<?php endif; ?>
		</a>



		<nav class="nav" aria-label="Primary">
			<button
				class="nav-hamburger"
				type="button"
				aria-expanded="false"
				aria-controls="nav-panel"
			>
				<span class="sr-only">Menu</span>
				<span class="nav-hamburger-icon" aria-hidden="true">
					<span class="nav-hamburger-bar"></span>
				</span>
			</button>

			<div class="nav-panel" id="nav-panel">
				<?php
    wp_nav_menu([
        'theme_location' => 'header-menu',
        'depth' => 2,
        'container' => false,
        'fallback_cb' => false,
        'walker' => new PreLaunch_Walker(),
        'items_wrap' => '<ul class="nav-list" role="list">%3$s</ul>',
    ]);
?>
			</div>
		</nav>
	</div>
</header>
<!-- End Navbar -->

<!--Start Body-->







