<?php

/**
 * Posts / template tags
 *
 * Small, reusable helpers for blog templates (cards, archives, single posts).
 * Keep these functions focused on rendering commonly repeated post meta and term lists.
 *
 * @link https://developer.wordpress.org/themes/basics/template-tags/
 * @link https://developer.wordpress.org/themes/basics/security/#escaping
 */

/**
 * Output post date markup.
 *
 * Prints a linked published date. If the post has been modified, also prints the
 * modified date in a <time> element.
 *
 * @param int|\WP_Post|null $post Post ID or object. Defaults to current post in the loop.
 * @param array            $args Optional arguments.
 * @return void
 */
function prelaunch_posted_on($post = null, $args = [])
{
    $post = get_post($post);

    if (! $post instanceof WP_Post) {
        return;
    }

    $defaults = [
        'class' => 'post-date',
    ];
    $args = array_merge($defaults, $args);

    $published_w3c = get_the_date(DATE_W3C, $post);
    $published_hum = get_the_date('', $post);

    $modified_w3c = get_the_modified_date(DATE_W3C, $post);
    $modified_hum = get_the_modified_date('', $post);

    $is_modified = ($published_w3c !== $modified_w3c);

    echo '<span class="' . esc_attr($args['class']) . '">';

    // Published date (linked to the post).
    echo '<a href="' . esc_url(get_permalink($post)) . '" rel="bookmark">';
    echo '<time class="published" datetime="' . esc_attr($published_w3c) . '">';
    echo esc_html($published_hum);
    echo '</time>';
    echo '</a>';

    // Modified date (not linked).
    if ($is_modified) {
        echo ' <time class="updated" datetime="' . esc_attr($modified_w3c) . '">';
        echo esc_html($modified_hum);
        echo '</time>';
    }

    echo '</span>';
}

/**
 * Output a term list for a taxonomy on the current post.
 *
 * @param string           $taxonomy Taxonomy name (e.g. 'category', 'post_tag').
 * @param array            $args     Optional arguments.
 * @param int|\WP_Post|null $post    Post ID or object. Defaults to current post in the loop.
 * @return void
 */
function prelaunch_post_terms($taxonomy, $args = [], $post = null)
{
    $post = get_post($post);

    if (! $post instanceof WP_Post) {
        return;
    }

    if (empty($taxonomy) || ! taxonomy_exists($taxonomy)) {
        return;
    }

    $defaults = [
        'class' => 'post-terms',
        'separator' => ', ',
        'before' => '',
        'after' => '',
    ];
    $args = array_merge($defaults, $args);

    $term_list = get_the_term_list(
        $post->ID,
        $taxonomy,
        $args['before'],
        $args['separator'],
        $args['after']
    );

    if (empty($term_list) || is_wp_error($term_list)) {
        return;
    }

    echo '<span class="' . esc_attr($args['class']) . '">';
    echo $term_list; // Term links are generated by WP; wrapper attributes are escaped above.
    echo '</span>';
}

/**
 * Return the post excerpt with a consistent fallback.
 *
 * Uses the manual excerpt when present; otherwise uses the generated excerpt.
 *
 * @param int|\WP_Post|null $post Post ID or object. Defaults to current post in the loop.
 * @return string
 */
function prelaunch_get_excerpt($post = null)
{
    $post = get_post($post);

    if (! $post instanceof WP_Post) {
        return '';
    }

    if (has_excerpt($post)) {
        return get_the_excerpt($post);
    }

    // get_the_excerpt() will generate from content when no manual excerpt exists.
    return get_the_excerpt($post);
}

/**
 * Return estimated reading time for a post.
 *
 * Calculates reading time based on word count of post content.
 * Defaults to 200 words per minute.
 *
 * @param int|\WP_Post|null $post Post ID or object. Defaults to current post.
 * @param array            $args Optional arguments.
 * @return string
 */
function prelaunch_get_reading_time($post = null, $args = [])
{
    $post = get_post($post);

    if (! $post instanceof WP_Post) {
        return '';
    }

    $defaults = [
        'words_per_minute' => 200,
        'suffix' => __('min read', 'prelaunch-wp'),
    ];
    $args = array_merge($defaults, $args);

    $content = get_post_field('post_content', $post->ID);

    if (empty($content)) {
        return '';
    }

    // Strip block comments and HTML.
    $content = wp_strip_all_tags($content);

    $word_count = str_word_count($content);

    if ($word_count === 0) {
        return '';
    }

    $minutes = (int) ceil($word_count / max(1, (int) $args['words_per_minute']));

    return sprintf(
        /* translators: %d: reading time in minutes */
        esc_html__('%d %s', 'prelaunch-wp'),
        $minutes,
        $args['suffix']
    );
}
